touch type
Asya-AV/Keyboard-trainer pull request #2
Opened 2024-04-10 18:20 UTC by Asya-AV

2024-04-11 10:06 UTC, KatyaProkhorchuk requested changes
надо немного поправить
планируешь ли реализовывать что-то на доп балы?

2024-04-11 10:06 UTC, KatyaProkhorchuk commented on main.py
> +class Test():
скобочки не нужны возле имени класса)

2024-04-11 10:06 UTC, KatyaProkhorchuk commented on main.py
> +class Test():
лучше вынести в test.py

2024-04-11 10:06 UTC, KatyaProkhorchuk commented on main.py
> +class FileUtils():
лучше вынести в fileutils.py

2024-04-11 10:06 UTC, KatyaProkhorchuk commented on main.py
> +class Console():
лучше вынести в console.py

2024-04-11 10:06 UTC, KatyaProkhorchuk commented on main.py
> +def end(stdsrc):
зачем stdsrc, если он не используется

2024-04-11 10:06 UTC, KatyaProkhorchuk commented on main.py
> +def game(stdsrc):
зачем stdsrc, если он не используется

2024-04-13 00:39 UTC, Asya-AV commented on main.py
> +def game(stdsrc):
Аргумент должен передаваться, иначе всплывает ошибка :( 
"TypeError: end() takes 0 positional arguments but 1 was given"

2024-04-25 09:21 UTC, KatyaProkhorchuk approved these changes
ок)

2025-09-04 12:40 UTC, merged